name: hyperlocal_booking_app
description: Hyper-local service booking app (single city)
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # Routing
  go_router: ^14.2.1

  # DI
  get_it: ^7.7.0

  # Backend
  supabase_flutter: ^2.6.1

  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Utils
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
